In [1]:
%load_ext autoreload
%autoreload 2
%matplotlib inline

import numpy as np
import jax
import fpfs
import pandas as pd
import jax.numpy as jnp
from jax import random
import lensPT

In [2]:
data = {'fpfs_M00': [1., 2., 3., 4.], 'fpfs_M22c': [5., 6., 7., 8.], 'fpfs_M22s': [3., 2., 1., 9.], 'fpfs_M40': [3., 2., 1., 9.]}
df = pd.DataFrame(data=data)
aa= df.to_records()
e1_lpt=lensPT.fpfs.E1(Const=1)
e2_lpt=lensPT.fpfs.E2(Const=1)

In [3]:
print(e1_lpt.evaluate(aa))
print(e1_lpt.grad(aa))
print(e1_lpt.hessian(aa))

[2.5  2.   1.75 1.6 ]
[[ 0.5        -1.25        0.        ]
 [ 0.33333334 -0.6666667   0.        ]
 [ 0.25       -0.4375      0.        ]
 [ 0.2        -0.32        0.        ]]
[[[ 0.         -0.25        0.        ]
  [-0.25        1.25        0.        ]
  [ 0.          0.          0.        ]]

 [[ 0.         -0.11111111  0.        ]
  [-0.11111111  0.44444445  0.        ]
  [ 0.          0.          0.        ]]

 [[ 0.         -0.0625      0.        ]
  [-0.0625      0.21875     0.        ]
  [ 0.          0.          0.        ]]

 [[ 0.         -0.04        0.        ]
  [-0.04        0.128       0.        ]
  [ 0.          0.          0.        ]]]


In [4]:
print(e2_lpt.evaluate(aa))
print(e2_lpt.grad(aa))
print(e2_lpt.hessian(aa))

[1.5       0.6666667 0.25      1.8      ]
[[ 0.5        -0.75        0.        ]
 [ 0.33333334 -0.22222222  0.        ]
 [ 0.25       -0.0625      0.        ]
 [ 0.2        -0.35999998  0.        ]]
[[[ 0.         -0.25        0.        ]
  [-0.25        0.75        0.        ]
  [ 0.          0.          0.        ]]

 [[ 0.         -0.11111111  0.        ]
  [-0.11111111  0.14814815  0.        ]
  [ 0.          0.          0.        ]]

 [[ 0.         -0.0625      0.        ]
  [-0.0625      0.03125     0.        ]
  [ 0.          0.          0.        ]]

 [[ 0.         -0.04        0.        ]
  [-0.04        0.14400001  0.        ]
  [ 0.          0.          0.        ]]]


In [5]:
e1_sq=e1_lpt*e1_lpt
print(e1_sq.evaluate(aa))
e1_sum=e1_lpt+e1_lpt
print(e1_sum.evaluate(aa))

[0.02777778 0.08163266 0.140625   0.19753087]
[0.33333334 0.5714286  0.75       0.8888889 ]


In [15]:
cov_mat= jnp.ones((3,3))
nb2 = lensPT.noise.noise_perturb2(e1_lpt,cov_mat)
print(nb2.evaluate(aa))

[0.375      0.11111111 0.046875   0.024     ]


In [18]:
sr1=lensPT.shear.g1_perturb1(e1_lpt)
print(sr1.evaluate(aa))
sr2=lensPT.shear.g2_perturb1(e1_lpt)
print(sr2.evaluate(aa))

[8.131728  5.656854  4.684582  2.9132798]
[0. 0. 0. 0.]
